# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='bar_code',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='articulos',
            field=models.ManyToManyField(blank=True, null=True, related_name='ventas', to='articulo.Articulo'),
        ),
    ]
