# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_auto_20180109_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('subtotal', models.FloatField()),
                ('descuento', models.FloatField()),
                ('total', models.FloatField()),
                ('articulos', models.ManyToManyField(blank=True, null=True, related_name='compras', to='articulo.Articulo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='articulo.Cliente')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.Sucursal')),
            ],
        ),
    ]
