# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0005_auto_20180322_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='pendiente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='articulos',
            field=models.ManyToManyField(blank=True, related_name='compras', to='articulo.Articulo', verbose_name='articulo_compra'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='articulos',
            field=models.ManyToManyField(blank=True, related_name='ventas', to='articulo.Articulo'),
        ),
    ]
