# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-20 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0006_auto_20180424_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='bar_code',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/'),
        ),
    ]
