from django.contrib import admin
from articulo.models import *

# Register your models here.
admin.site.register(EspejueloGraduado)
admin.site.register(GafaSol)
admin.site.register(Accesorio)
admin.site.register(LenteContacto)
admin.site.register(CristalGraduado)
admin.site.register(Sucursal)
admin.site.register(Medicion)
admin.site.register(Marca)
admin.site.register(TratamientoCristal)
admin.site.register(Modelo)
admin.site.register(Color)
admin.site.register(TipoArmazon)
admin.site.register(TipoMontura)
admin.site.register(MaterialArmadura)
admin.site.register(MaterialCristal)
admin.site.register(MaterialSol)
admin.site.register(Proveedor)
admin.site.register(Doctor)
admin.site.register(Cliente)
admin.site.register(Receta)
admin.site.register(Venta)